name: Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: msouthwick.com
          username: matthias
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: source ~/.nvm/nvm.sh && bash /home/matthias/Github/familyappupdate.sh
